#!/usr/bin/env python
"""
Emit the batch results as LaTeX macros so the write-up never drifts from the data.

`out/batch_summary.json` is the single source of truth. This writes
`couinaud_results.tex` containing:

  * scalar macros  -- \\resNCases, \\resRho, \\resDiceMHV, ... for inline prose
  * table macros   -- \\resFrameTable, \\resCheckTable, \\resVolumeTable, ...

so `couinaud.tex` can say "\\resRho" in a sentence and "\\resVolumeTable" where a
table belongs, and re-running this script after a new batch updates both. Nothing
here is authored prose; the interpretation lives in the document.

    python export_latex.py [--out ../../couinaud_results.tex] [--figures ../../figures/couinaud]
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path

import numpy as np

from couinaud import (SEG_DESCRIPTION, SEG_IDS, SEG_NAMES, SEG_REFERENCE_MEAN_SD,
                      SEG_REFERENCE_PCT)

HERE = Path(__file__).resolve().parent
OUT = HERE / "out"

# Couinaud sector groupings, with the reference share summed from the same source
# as the per-segment means (Leelaudomlipi et al. 2002).
SECTORS = [
    ("left liver", (2, 3, 4)),
    ("right anterior sector", (5, 8)),
    ("right posterior sector", (6, 7)),
    ("caudate", (1,)),
]

FIGURES = {
    "orientation": "1_orientation.png",
    "geometry": "2_geometry.png",
    "territories": "3_seeds_territories.png",
    "segments": "4_segments.png",
    "volumes": "5_volumes.png",
    "modes": "6_modes.png",
    "assignment": "7_assignment.png",
}


def tex(s: str) -> str:
    """Escape a plain string for LaTeX text mode."""
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def roman(seg: int) -> str:
    return f"\\textsc{{{SEG_NAMES[seg].lower()}}}"


def load() -> dict:
    path = OUT / "batch_summary.json"
    if not path.exists():
        raise SystemExit(f"{path} not found -- run `python run_couinaud.py --all` first")
    return json.loads(path.read_text())


def load_ablation() -> dict | None:
    """
    The propagation-rule ablation, if it has been run.

    Optional on purpose: the document must still build from the batch alone, so a
    missing ablation degrades to a stated absence rather than an undefined macro.
    """
    for name in ("ablation2.json", "ablation.json"):
        path = OUT / name
        if path.exists():
            data = json.loads(path.read_text())
            data["_source"] = name
            return data
    return None


def median_iqr(values) -> tuple[float, float, float]:
    v = np.asarray(values, dtype=float)
    return float(np.median(v)), float(np.percentile(v, 25)), float(np.percentile(v, 75))


def build(summary: dict) -> str:
    cases = summary["cases"]
    failures = summary["failures"]
    bias = summary.get("coverage_bias", {})
    n = len(cases)

    out: list[str] = []
    add = out.append

    add("% ------------------------------------------------------------------")
    add("% Generated by continuity/couinaud/export_latex.py -- do not edit by hand.")
    add(f"% Source: out/batch_summary.json, {n} cases.")
    add("% ------------------------------------------------------------------")
    add("")

    def macro(name: str, value: str) -> None:
        add(f"\\newcommand{{\\{name}}}{{{value}}}")

    # ---- scalars ----------------------------------------------------------
    add("% --- scalar results, for inline use in prose ---")
    macro("resNCases", str(n))
    macro("resNFailed", str(len(failures)))
    macro("resNAttempted", str(n + len(failures)))
    total_checks = sum(len(c["checks"]["rows"]) for c in cases)
    total_passed = sum(c["checks"]["passed"] for c in cases)
    macro("resChecksPassed", str(total_passed))
    macro("resChecksTotal", str(total_checks))
    macro("resChecksPct", f"{100 * total_passed / max(total_checks, 1):.0f}")

    def metric_macro(key: str, stem: str) -> tuple[float, float, float, int] | None:
        vals = [c["checks"]["metrics"].get(key) for c in cases]
        vals = [v for v in vals if v is not None]
        if not vals:
            return None
        med, q1, q3 = median_iqr(vals)
        macro(f"res{stem}", f"{med:.2f}")
        macro(f"res{stem}Full", f"{med:.3f}")
        macro(f"res{stem}IQR", f"{q1:.2f}--{q3:.2f}")
        macro(f"res{stem}N", str(len(vals)))
        return med, q1, q3, len(vals)

    dice_mhv = metric_macro("dice_cantlie_vs_mhv", "DiceMHV")
    dice_rhv = metric_macro("dice_right_sector_vs_rhv", "DiceRHV")
    dice_lhv = metric_macro("dice_segment_iv_vs_lhv", "DiceLHV")
    metric_macro("mode_agreement", "ModeAgreement")

    if bias.get("pearson_log") is not None:
        macro("resRho", f"{bias['pearson_log']:.2f}")
        macro("resRhoN", str(bias["n"]))
        macro("resVolRatio", f"{bias['volume_ratio_median']:.2f}")
        macro("resVolRatioRef", f"{bias['volume_ratio_reference']:.2f}")
        macro("resSeedRatio", f"{bias['seed_ratio_median']:.2f}")

    # split-method census, straight from the notes each run leaves behind
    graph_cuts = relaxed = plane = median_fb = 0
    for c in cases:
        for note in c["notes"]:
            if "relaxed graph cut splits" in note:
                relaxed += 1
            elif "graph cut splits" in note:
                graph_cuts += 1
            elif "no usable graph cut ->" in note:
                plane += 1
            elif "is degenerate -> median" in note:
                median_fb += 1
    total_splits = graph_cuts + relaxed + plane + median_fb
    macro("resSplitGraph", str(graph_cuts))
    macro("resSplitRelaxed", str(relaxed))
    macro("resSplitPlane", str(plane))
    macro("resSplitMedian", str(median_fb))
    macro("resSplitTotal", str(total_splits))
    macro("resSplitGraphPct",
          f"{100 * (graph_cuts + relaxed) / max(total_splits, 1):.0f}")

    # how often each scissura could be fitted at all
    for key, stem in (("mhv", "MHV"), ("rhv", "RHV"), ("lhv", "LHV")):
        have = sum(1 for c in cases if key in c.get("planes", []))
        macro(f"resPlane{stem}", str(have))
        macro(f"resNoPlane{stem}", str(n - have))

    low_conf = [c for c in cases if c["frame_confidence"] < 0.62]
    macro("resLowConfidence", str(len(low_conf)))
    conf_med, conf_q1, conf_q3 = median_iqr([c["frame_confidence"] for c in cases])
    macro("resFrameConfidence", f"{conf_med:.2f}")
    macro("resFrameConfidenceIQR", f"{conf_q1:.2f}--{conf_q3:.2f}")

    left = [sum(c["volume_pct"][str(i)] for i in (2, 3, 4)) for c in cases]
    macro("resLeftLiverPct", f"{np.median(left):.0f}")
    add("")

    # ---- frame table ------------------------------------------------------
    frames: dict[str, int] = {}
    for c in cases:
        frames[c["frame"].split(" (")[0]] = frames.get(c["frame"].split(" (")[0], 0) + 1
    rows = []
    for key, count in sorted(frames.items(), key=lambda kv: -kv[1]):
        axes = dict(re.findall(r"([RAS])=axis(\d[+-])", key))
        pretty = " & ".join(f"\\texttt{{axis {axes.get(c, '?')[0]}{axes.get(c, '?')[1]}}}"
                            for c in "RAS")
        rows.append(f"{pretty} & {count} \\\\")
    add("% --- recovered anatomical frame across the cohort ---")
    add("\\newcommand{\\resFrameTable}{%")
    add("\\begin{table}[H]")
    add("\\centering")
    add("\\caption{Effective anatomical frame recovered from the anatomy, across the "
        f"{n} segmented cases. Every one of them declares axcodes "
        "\\texttt{(R,A,S)} in its NIfTI header.}")
    add("\\label{tab:frames}")
    add("\\begin{tabular}{llll}")
    add("\\toprule")
    add("right & anterior & superior & cases \\\\")
    add("\\midrule")
    out.extend(rows)
    add("\\bottomrule")
    add("\\end{tabular}")
    add("\\end{table}}")
    add("")

    # ---- check table ------------------------------------------------------
    tally: dict[str, list[int]] = {}
    order: list[str] = []
    for c in cases:
        for name, ok, _ in c["checks"]["rows"]:
            short = name.split(" (Dice")[0].split(" (>=")[0]
            if short not in tally:
                tally[short] = [0, 0]
                order.append(short)
            tally[short][0] += int(bool(ok))
            tally[short][1] += 1
    add("% --- per-check pass rates ---")
    add("\\newcommand{\\resCheckTable}{%")
    add("\\begin{table}[H]")
    add("\\centering")
    add(f"\\caption{{Sanity-check pass rates across the {n} segmented cases. "
        "The structural checks are invariants the pipeline must never break; the "
        "anatomical ones are relations that hold in every human liver; the "
        "independent ones compare portal-derived boundaries against hepatic-vein "
        "planes fitted from labels the assignment never sees.}")
    add("\\label{tab:checks}")
    add("\\begin{tabular}{lr}")
    add("\\toprule")
    add("check & passed \\\\")
    add("\\midrule")
    for name in order:
        passed, avail = tally[name]
        add(f"{tex(name)} & {passed}/{avail} \\\\")
    add("\\bottomrule")
    add("\\end{tabular}")
    add("\\end{table}}")
    add("")

    # ---- cross-validation table -------------------------------------------
    add("% --- independent cross-validation ---")
    add("\\newcommand{\\resDiceTable}{%")
    add("\\begin{table}[H]")
    add("\\centering")
    add("\\caption{Independent cross-validation. Each portal-derived boundary is "
        "compared by Dice against the corresponding hepatic-vein plane, which is "
        "fitted from labels the assignment never uses. Always evaluated on the "
        "Voronoi labelling: in hybrid mode the sector boundaries \\emph{are} the "
        "vein planes, so the comparison would return $1$ by construction.}")
    add("\\label{tab:dice}")
    add("\\begin{tabular}{lrrr}")
    add("\\toprule")
    add("comparison & median Dice & IQR & $n$ \\\\")
    add("\\midrule")
    for label, res in (("portal left/right vs.\\ the MHV (Cantlie) plane", dice_mhv),
                       ("portal anterior/posterior vs.\\ the RHV plane", dice_rhv),
                       ("segment \\textsc{iv} boundary vs.\\ the LHV plane", dice_lhv)):
        if res is None:
            continue
        med, q1, q3, cnt = res
        add(f"{label} & {med:.3f} & {q1:.2f}--{q3:.2f} & {cnt} \\\\")
    add("\\bottomrule")
    add("\\end{tabular}")
    add("\\end{table}}")
    add("")

    # ---- per-segment volumetry --------------------------------------------
    add("% --- per-segment volume shares ---")
    add("\\newcommand{\\resVolumeTable}{%")
    add("\\begin{table}[H]")
    add("\\centering")
    add(f"\\caption{{Segment volume as a share of total liver, median across {n} "
        "cases, against Leelaudomlipi et al.\\ (\\emph{Liver Transplantation} 2002, "
        "$n=155$ living donors). The acceptance band is $\\mu\\pm2\\sigma$, wide on "
        "purpose: inter-subject variation in segment volume is genuinely large, so "
        "this catches gross failure and nothing finer.}")
    add("\\label{tab:volumes}")
    add("\\begin{tabular}{llrrrrr}")
    add("\\toprule")
    add("seg & territory & median \\% & IQR & $\\mu$ \\% & $\\mu\\pm2\\sigma$ & in band \\\\")
    add("\\midrule")
    for s in SEG_IDS:
        vals = [c["volume_pct"][str(s)] for c in cases]
        med, q1, q3 = median_iqr(vals)
        lo, hi = SEG_REFERENCE_PCT[s]
        mu, _ = SEG_REFERENCE_MEAN_SD[s]
        inb = sum(1 for v in vals if lo <= v <= hi)
        add(f"{roman(s)} & {tex(SEG_DESCRIPTION[s])} & {med:.1f} & {q1:.1f}--{q3:.1f} "
            f"& {mu:.1f} & {lo:.1f}--{hi:.1f} & {inb}/{n} \\\\")
    add("\\bottomrule")
    add("\\end{tabular}")
    add("\\end{table}}")
    add("")

    # ---- sector volumetry --------------------------------------------------
    add("% --- sector volume shares, where the bias is legible ---")
    add("\\newcommand{\\resSectorTable}{%")
    add("\\begin{table}[H]")
    add("\\centering")
    add("\\caption{Sector volume share. Aggregating to sectors removes the "
        "superior/inferior cut from the comparison and isolates what the nearest-seed "
        "assignment does with the territory as a whole. $\\Delta$ is the median minus "
        "the reference.}")
    add("\\label{tab:sectors}")
    add("\\begin{tabular}{llrrrr}")
    add("\\toprule")
    add("sector & segments & median \\% & IQR & reference \\% & $\\Delta$ \\\\")
    add("\\midrule")
    for label, ids in SECTORS:
        vals = [sum(c["volume_pct"][str(i)] for i in ids) for c in cases]
        med, q1, q3 = median_iqr(vals)
        ref = sum(SEG_REFERENCE_MEAN_SD[i][0] for i in ids)
        names = "+".join(SEG_NAMES[i] for i in ids)
        add(f"{tex(label)} & \\textsc{{{names.lower()}}} & {med:.1f} & "
            f"{q1:.1f}--{q3:.1f} & {ref:.1f} & ${med - ref:+.1f}$ \\\\")
    add("\\bottomrule")
    add("\\end{tabular}")
    add("\\end{table}}")
    add("")

    # ---- split-method census ----------------------------------------------
    add("% --- which mechanism actually decided each binary split ---")
    add("\\newcommand{\\resSplitTable}{%")
    add("\\begin{table}[H]")
    add("\\centering")
    add(f"\\caption{{How each of the {total_splits} binary subdivisions across the "
        "cohort was decided. The cascade tries the graph cut first and falls back "
        "only when no cut is convincing or the result would be degenerate.}")
    add("\\label{tab:splits}")
    add("\\begin{tabular}{lrr}")
    add("\\toprule")
    add("mechanism & splits & share \\\\")
    add("\\midrule")
    for label, count in (("graph cut", graph_cuts), ("relaxed graph cut", relaxed),
                         ("plane threshold (fallback)", plane),
                         ("median projection (last resort)", median_fb)):
        add(f"{label} & {count} & {100 * count / max(total_splits, 1):.0f}\\% \\\\")
    add("\\midrule")
    add(f"\\textbf{{total}} & \\textbf{{{total_splits}}} & \\\\")
    add("\\bottomrule")
    add("\\end{tabular}")
    add("\\end{table}}")
    add("")

    # ---- failures ----------------------------------------------------------
    add("% --- cases the pipeline refused or flagged ---")
    add("\\newcommand{\\resFailureList}{%")
    if failures or low_conf:
        add("\\begin{itemize}[leftmargin=*]")
        for name, err in failures:
            reason = err.split(": ", 1)[-1].rstrip("')\"")
            add(f"\\item \\texttt{{{tex(name)}}} --- refused: {tex(reason)}.")
        if low_conf:
            names = ", ".join(f"\\texttt{{{tex(c['case'])}}}" for c in low_conf)
            add(f"\\item Low frame confidence ($<0.62$), segmented but flagged: {names}.")
        add("\\end{itemize}")
    else:
        add("No case was refused and none was flagged.")
    add("}")
    add("")

    return "\n".join(out) + "\n"


# Arm key -> (row label, short prose description) for the ablation table. Kept here
# rather than imported from ablate.py so a stale JSON still renders with the labels
# the run was made under.
ARM_LABELS = {
    "base": "straight-line nearest seed",
    "geo": "geodesic",
    "geo+flow50": "geodesic $+$ flow, $\\alpha=0.5$",
    "geo+flow100": "geodesic $+$ flow, $\\alpha=1$ (Murray)",
    "geo+flow150": "geodesic $+$ flow, $\\alpha=1.5$",
    "geo+flow25": "geodesic $+$ flow, $\\alpha=0.25$",
    "geo+flow75": "geodesic $+$ flow, $\\alpha=0.75$",
    "geo+vein2": "geodesic $+$ vein barrier $\\times2$",
    "geo+vein5": "geodesic $+$ vein barrier $\\times5$",
    "all": "geodesic $+$ flow $+$ vein barrier",
}


def build_ablation(ab: dict) -> str:
    """Macros for the propagation-rule ablation."""
    summary = ab["summary"]
    out: list[str] = []
    add = out.append

    def macro(name: str, value: str) -> None:
        add(f"\\newcommand{{\\{name}}}{{{value}}}")

    add("% --- propagation-rule ablation ---")
    add(f"% Source: out/{ab['_source']}.")
    order = [k for k in ARM_LABELS if k in summary]
    base, geo = summary.get("base", {}), summary.get("geo", {})

    def num(d, key, fmt=".3f"):
        v = d.get(key)
        return format(v, fmt) if v is not None and np.isfinite(v) else "--"

    macro("abNArms", str(len(order)))
    macro("abBaseErr", num(base, "sector_err"))
    macro("abBaseRho", num(base, "rho", ".2f"))
    macro("abGeoErr", num(geo, "sector_err"))
    macro("abGeoRho", num(geo, "rho", ".2f"))
    for key, tag in (("base", "Base"), ("geo", "Geo")):
        s = summary.get(key, {})
        macro(f"ab{tag}Blob", f"{s.get('one_blob', 0)}/{s.get('n', 0)}")
        macro(f"ab{tag}Band", f"{s.get('in_band', 0)}/{s.get('n', 0)}")
    # the flow arms, in increasing alpha, are the coverage-bias evidence
    flow = [k for k in order if k.startswith("geo+flow")]
    if flow:
        macro("abRhoLadder", " $\\to$ ".join(
            [num(base, "rho", ".2f")] + [num(summary[k], "rho", ".2f") for k in flow]))
        macro("abErrLadder", " $\\to$ ".join(
            [num(base, "sector_err")] + [num(summary[k], "sector_err") for k in flow]))
    vein = next((k for k in order if k.startswith("geo+vein")), None)
    if vein:
        macro("abVeinErr", num(summary[vein], "sector_err"))
    add("")

    add("\\newcommand{\\resAblationTable}{%")
    add("\\begin{table}[H]")
    add("\\centering")
    add("\\caption{Propagation-rule ablation. The same seed labels, carried to the "
        "parenchyma under each rule. \\emph{sector err} is the median "
        "$|\\log|$ distance of $(\\textsc{vi}+\\textsc{vii})/(\\textsc{v}+\\textsc{viii})$ "
        "from the published $0.83$ and $\\rho$ is the coverage bias, both lower-is-better. "
        "A vein that fed the assignment cannot then judge it, so its Dice is refused "
        "rather than reported: those cells read \\emph{spent}.}")
    add("\\label{tab:ablation}")
    add("\\begin{tabular}{lrrrrrrr}")
    add("\\toprule")
    add("rule & sector err & ratio & $\\rho$ & Dice RHV & Dice MHV & one blob & in band \\\\")
    add("\\midrule")
    for key in order:
        s = summary[key]
        spent = set(s.get("spent", []))
        cells = []
        for metric, vein_key in (("dice_rhv", "rhv"), ("dice_mhv", "mhv")):
            cells.append("\\emph{spent}" if vein_key in spent else num(s, metric))
        add(f"{ARM_LABELS[key]} & {num(s, 'sector_err')} & {num(s, 'sector_ratio', '.2f')} "
            f"& {num(s, 'rho', '.2f')} & {cells[0]} & {cells[1]} "
            f"& {s.get('one_blob', 0)}/{s.get('n', 0)} & {s.get('in_band', 0)}/{s.get('n', 0)} \\\\")
    add("\\bottomrule")
    add("\\end{tabular}")
    add("\\end{table}}")
    add("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=HERE.parent.parent / "couinaud_results.tex")
    ap.add_argument("--figures", type=Path, default=HERE.parent.parent / "figures" / "couinaud")
    ap.add_argument("--case", default=None,
                    help="case whose figures to copy (default: the first one with a full set)")
    args = ap.parse_args()

    summary = load()
    body = build(summary)
    ablation = load_ablation()
    if ablation is not None:
        body += "\n" + build_ablation(ablation)
        print(f"included the ablation from out/{ablation['_source']}")
    else:
        print("no ablation JSON found -- run `python ablate.py` to include it")
    args.out.write_text(body)
    print(f"wrote {args.out}")

    case = args.case
    if case is None:
        for d in sorted(OUT.glob("RMV*")):
            if d.is_dir() and all((d / f).exists() for f in FIGURES.values()):
                case = d.name
                break
    if case is None:
        print("no case has a full figure set -- run `python run_couinaud.py <case>` first")
        return 0

    args.figures.mkdir(parents=True, exist_ok=True)
    for stem, fname in FIGURES.items():
        src = OUT / case / fname
        if src.exists():
            shutil.copy2(src, args.figures / f"couinaud_{stem}.png")
    batch = OUT / "batch_summary.png"
    if batch.exists():
        shutil.copy2(batch, args.figures / "couinaud_batch.png")
    print(f"copied figures for {case} -> {args.figures}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
